version: '3.8'

services:
  postgres:
    build: ./backend/database
    image: postgres
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend
    expose:
      - '${POSTGRES_PORT}'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  client_server_net:
    driver: bridge
  backend:
    driver: bridge