export const dummyDms = [
    {
        "id": 0,
        "firstName": "Hellis",
        "lastName": "Smith",
        "profilePicture": "/imgs/test.jpg",
        "lastMessage": "Hello, I just wanna tell that your task has been done and you should contact",
        isFavorite: false,
    },
    {
        "id": 1,
        "firstName": "Jane",
        "lastName": "Smith",
        "profilePicture": "/imgs/Avatar.png",
        "lastMessage": "Are we still on for the meeting tomorrow?",
        isFavorite: true,
    },
    {
        "id": 2,
        "firstName": "John",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder1.jpg",
        "lastMessage": "Don't forget to check the report I sent you.",
        isFavorite: false,
    },
    {
        "id": 3,
        "firstName": "Alice",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder.jpg",
        "lastMessage": "Great job on the presentation today!",
        isFavorite: true,
    },
    {
        "id": 4,
        "firstName": "Bob",
        "lastName": "Smith",
        "profilePicture": "/imgs/Avatar.png",
        "lastMessage": "Can we reschedule our call?",
        isFavorite: false,
    },
    {
        "id": 5,
        "firstName": "Charlie",
        "lastName": "Smith",
        "profilePicture": "/imgs/test.jpg",
        "lastMessage": "I'll send over the documents by EOD.",
        isFavorite: false,
    },
    {
        "id": 6,
        "firstName": "Diana",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder2.jpg",
        "lastMessage": "Looking forward to our lunch meeting.",
        isFavorite: false,
    },
    {
        "id": 7,
        "firstName": "Edward",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder3.jpg",
        "lastMessage": "Could you review the latest draft?",
        isFavorite: false,
    },
    {
        "id": 8,
        "firstName": "Diana",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder2.jpg",
        "lastMessage": "Looking forward to our lunch meeting.",
        isFavorite: true,
    },
    {
        "id": 9,
        "firstName": "Edward",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder3.jpg",
        "lastMessage": "Could you review the latest draft?",
        isFavorite: false,
    },
    {
        "id": 10,
        "firstName": "Edward",
        "lastName": "Smith",
        "profilePicture": "/imgs/man_placeholder3.jpg",
        "lastMessage": "Could you review the latest draft?",
        isFavorite: true,
    }
]