FROM postgres:latest

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext

# Copy the initialization template and script
COPY init.sql.template /docker-entrypoint-initdb.d/
COPY init.sh /docker-entrypoint-initdb.d/
COPY conf/postgresql.conf /etc/postgresql/postgresql.conf
RUN chmod +x /docker-entrypoint-initdb.d/init.sh

# Set the entrypoint to the official PostgreSQL entrypoint script
ENTRYPOINT ["/docker-entrypoint-initdb.d/init.sh"]
